Add - 각 앱 모델링 추가
wecode-bootcamp-korea/28-2nd-BANGGUSEOK-Traveller-backend pull request #1
Opened 2022-01-11 08:10 UTC by Bruno-Jang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 각 앱 모델링 작성했습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 경래님 리뷰를 참고해서 모델링 작성했습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- ERD 작성시 정규화에 대해 고민하며 적용하면서 어떤 경우에 정규화가 더 필요할지 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- products 테이블 -- products_tags 중간테이블 -- tags 테이블
  이렇게 연결되어 있어서 products 테이블에 ManyToManyField(through='ProductTag')를 설정해뒀습니다.
  이렇게 해야 product의 id를 기준으로 tag 값을 정참조처럼 점('.')만 찍어서 데이터를 가져올 수 있는걸로 알고 그렇게 설정했는데
  맞게 한건가 싶어서 질문 드립니다.

2022-01-11 08:38 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2022-01-11 08:38 UTC, kyeongraekim commented on products/models.py
> +    menu        = models.ForeignKey('Menu', on_delete=models.CASCADE)
user와 menu가 항목에서 제거가 된다면  해당 상품도 같이 사라져야할까요? 해당 내용 한 번 고민해보세요!~

2022-01-11 08:38 UTC, kyeongraekim commented on products/models.py
> +    updated_at  = models.DateTimeField(auto_now=True)
자주사용되는 생성및 수정 이력 관리는 TimeStampModel을 사용하여서 클래스 추상화를 해보세요~

2022-01-11 08:38 UTC, kyeongraekim commented on products/models.py
> +    product   = models.OneToOneField('Product', on_delete=models.CASCADE)
products에서 1v1필드로 MainImage와 연결되는 것이 더 나은 기획 같아 보이네요!~ 그렇게 판단한 이유를 한 번 고민해보세요!~

2022-01-11 08:38 UTC, kyeongraekim commented on products/models.py
> +        db_table = 'mproduct_tags'
테이블명 설정에 오타가 보이는 것 같네요!~

2022-01-11 08:38 UTC, kyeongraekim commented on users/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
이곳도 Product처럼 추상화된 클래스를 상속받으면 생략될 수 있겠네요!~

2022-01-11 08:38 UTC, kyeongraekim commented on votes/models.py
> +    is_voted               = models.BooleanField()
불리언 값의 default 값을 설정해주세요!~

2022-01-11 09:56 UTC, Bruno-Jang commented on products/models.py
> +    product   = models.OneToOneField('Product', on_delete=models.CASCADE)
경래님 products 테이블에서 1v1필드로 MainImage와 연결시키는게 어떤 점에서 더 나은건지 모르겠습니다..

그리고 경래님 products 테이블에 main_image  = models.OneToOneField('MainImage', on_delete=models.CASCADE)
이렇게 입력하면 메인이미지가 삭제될 경우 제품도 같이 삭제될거라는 생각이 들어서
main_image  = models.OneToOneField('MainImage', on_delete=moels.SET_NULL, null=True)로 할까도 고민했는데
이렇게 할거면 MainImage를 정규화하지 않는 방법을 쓰거나 정규화를 할 경우에는 해당 테이블에 1v1필드를 두는게 데이터를 입력할 때도 낫지 않을까하여 질문 드리고 싶습니다.
우선 밤 동안에 좀 더 찾아보고 고민해보겠습니다..!

2022-01-11 12:16 UTC, Bruno-Jang commented on products/models.py
> +    product   = models.OneToOneField('Product', on_delete=models.CASCADE)
product가 삭제될 경우에 메인 이미지와 서브 이미지들이 같이 지워지게 하는게 맞는것 같아서 이렇게 설정했습니다~!

2022-01-11 12:31 UTC, kyeongraekim commented on products/models.py
> +    product   = models.OneToOneField('Product', on_delete=models.CASCADE)
우경님~ OneToOneField로 main image를 프로덕트가 보고 있게 되면, 위에 써주신대로 정참조 형식으로 이미지를 가져 올 수 있어서 더 편하게 코드를 진행하실 수 있으실 겁니다. 일대일 관계에서의 참조 방향성을 따져보시면 왜 역참조보다 정참조가 더 나을 지 더 명확히 이해가 되실 거에요!~

2022-01-11 12:33 UTC, kyeongraekim commented on products/models.py
> +    product   = models.OneToOneField('Product', on_delete=models.CASCADE)
기타 질문 및 특이사항에 대한 대답으로 ManyToMany 필드내에서 awwards 사이트 특성상 tag를 기준으로 product를 불러올 수 있어야되고 동시에 product를 기준으로도 불러 올 수 있어야 합니다. Shell에서 양 방향에서 어떻게 서로를 불러 올 수 있을지 많이 찍어보시는 것을 추천드려요!~

2022-01-12 02:03 UTC, kyeongraekim approved these changes
LGTM!~ 추후에 모델링 수정 사항이 생기면 브랜치 새로 파서 푸시해주심을 잊지 말아주세요!~

2022-01-12 02:04 UTC, merged