ADD: 상품 디테일 페이지
wecode-bootcamp-korea/28-2nd-BANGGUSEOK-Traveller-backend pull request #3
Opened 2022-01-13 07:04 UTC by seinthemag

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 상세 페이지

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 지정한 url을 통해 GET method로 상품의 상세 정보 조회
2. 조회한 데이터와 상태코드 200 리턴
3. 존재하지 않는 상품일 시 에러코드 리턴
4. unit test
- GET요청 성공시
- 상품 미존재시 

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 일대다, 다대다 관계의 테이블을 참조해 필요한 정보만 가져오기 위한 방법에 대해 고민했습니다.
- 해당되는 부분의 개념에 대한 이해가 아직 부족한 것 같아 개인적으로 다시 한번 정리해보겠습니다.
<br />

## :: 기타 질문 및 특이 사항
- 유닛 테스트에서 이상이 없는걸 확인했지만 제가 작성한 방법이 맞는 방법인지 확신이 서지 않습니다. 보다 효율적이고 좋은 방법이 없을지 궁금합니다.
- 현재 미완성 상태로, 다른 앱의 view부분이 완성되면 추가적으로 기능구현할 예정입니다. 지금 상태에서 수정할 부분들에 대해 지적해주시면 반영하여 수정하겠습니다.

2022-01-13 07:55 UTC, kyeongraekim requested changes
세인님 아래 내용 확인 하신 후 수정 반영해주세요!~

2022-01-13 07:55 UTC, kyeongraekim commented on products/tests.py
> +        )
같은 테이블에 여러 객체가 한 번에 들어가는 구조네요!~ 조금 더 많이 목데이터를 만들어 보신 후, bulk_create에 한 번 도전해보세요!~

2022-01-13 07:55 UTC, kyeongraekim commented on products/tests.py
> +            'result1': {
키값에 result1 이라는 표현이 다소 어색해보이네요.. 숫자를 제거하는 건 어떨까요?

2022-01-13 07:55 UTC, kyeongraekim commented on products/tests.py
> +        self.assertEqual(response.status_code, 400)
존재하지 않는 리소스에 대한 접근이니 더 올바른 에러코드가 있을 것 같아 보이네요!

2022-01-13 07:55 UTC, kyeongraekim commented on products/tests.py
> +    def test_detail_get_not_exist(self):
전체적으로 훑어 보신 후 test 함수명에 success/fail을 명시해주세요~ 예를들어 
```test_fail_'원래 함수명'_when_the_product_does_not_exist ```

정도가 될 수 있겠네요

2022-01-13 07:55 UTC, kyeongraekim commented on products/views.py
> +            return JsonResponse({'result1': data}, status = 200)
위 테스트 코드에서의 어색한 result1의 원인이 여기 있었군요! 충분히 고민 해 보신 후 수정 부탁드려요!~

2022-01-13 07:55 UTC, kyeongraekim commented on products/views.py
> +            sub_images = SubImage.objects.filter(product_id=product.id)
해당 product_id에 맞물리는 sub_image 가 없을 경우를 대비해 if 문과 .exists() 메소드르 사용하여 미리 핸들링을 해줄 필요가 있어보이네요!~

2022-01-13 08:37 UTC, kyeongraekim commented
추가로 다음 푸시 때부터는 꼭 리베이스 이후에 올려주세요!~

2022-01-13 12:35 UTC, seinthemag commented
경래님, 남겨주신 리뷰 반영하여 수정 후 리베이스해서 푸쉬했습니다!

2022-01-14 01:56 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요 세인님!~

2022-01-14 01:56 UTC, kyeongraekim commented on products/views.py
> +                return JsonResponse({'message': 'IMAGES_DOES_NOT_EXIST'}, status = 400)
Images 복수형이니 DO NOT 으로 작성하는게 영문법에 맞는 표현이겠네요~ 아니면 IMAGE DOES NOT EXIST 도 괜찮겠습니다~  ㅎㅎ 마이너한 부분이지만 피드백 남깁니다~

2022-01-14 01:56 UTC, kyeongraekim commented on products/tests.py
> +from .models      import *
import * 표현보다는 원하는 모델을 직접 명시하여 불러오는 습관을 들여주세요!~ 지금은 괜찮을 수 있지만 추후에 프로젝트가 커지게 된다면 중간에 의도치 않은 꼬임현상이 발생할 수 있습니다 ㅎㅎ

아래 링크 참고하여 확인해주세요!~
https://www.geeksforgeeks.org/why-import-star-in-python-is-a-bad-idea/

2022-01-14 01:56 UTC, kyeongraekim commented on products/tests.py
> +
유닛테스트는 발생가능한 에러/실패의 경우의수를 최대한 고려하여서 모두 작성해주셔야 합니다. 아래 image does not exist 예외처리를 새롭게 리뷰를 반영하며 추가해주셨는데 해당 내용이 잘 핸들링 되는지 테스트 케이스에 추가시켜주셔야겠죠?

2022-01-14 01:56 UTC, kyeongraekim commented on products/tests.py
> +            )for i in range(5)]
bulk create를 잘 적용해주셨네요!~ 다만  각 테스트 케이스들의 수정/확인 등이 용이하게끔 목데이터를 직접 작성해주는 방향으로 작성해주셨으면 합니다. 아래 예시를 참고해주세요!~
아래 image 관련 does not exist 에러 핸들링을 위해서는 각각의 데이터를 커스터마이징 할 수 있어야 할 것 같네요~

```python
 user_list = [
            User(
                id               = 1,
                account_email    = 'email1@test.com',
                profile_nickname = 'ridi1'
            ),
            User(
                id               = 2,
                account_email    = 'email2@test.com',
                profile_nickname = 'ridi1'
            ),
            User(
                id               = 3,
                account_email    = 'email3@test.com',
                profile_nickname = 'ridi1'
            ),
            User(
                id               = 4,
                account_email    = 'email4@test.com',
                profile_nickname = 'ridi1'
            ),
            User(
                id               = 5,
                account_email    = 'email5@test.com',
                profile_nickname = 'ridi1'
            )
        ]
        User.objects.bulk_create(user_list)

2022-01-14 06:39 UTC, seinthemag commented
경래님 리뷰 반영하여 수정하였습니다. 확인 부탁드립니다!

2022-01-14 07:13 UTC, kyeongraekim approved these changes
LGTM!~

2022-01-14 07:13 UTC, merged