[HELP] 로그인 unit test 중 IntegrityError 메세지 issue
wecode-bootcamp-korea/28-2nd-BANGGUSEOK-Traveller-backend pull request #4
Opened 2022-01-13 11:37 UTC by Bruno-Jang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 프론트와 통신은 성공했으나 unit test에서 계속 에러가 떠서 질문 드립니다..

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 

<br />

## :: 기타 질문 및 특이 사항
- 경래님 unit test 중에 계속 같은 에러메세지가 떠서 찾다찾다 모르겠어서 질문 드립니다..
  아래의 메세지인데 모델링에서 null 과 blank에 True를 줘야한다는 얘기들이 많던데 그게 근본적인 해결책인지 의심이 들어서 질문드립니다. 
  django.db.utils.IntegrityError: (1048, "Column 'kakao_id' cannot be null") 방향만이라도 알려주시면 감사하겠습니다ㅠ

2022-01-14 04:54 UTC, Bruno-Jang commented
잘못된 부분 찾아서 수정 거의 다 끝났습니다.
곧 다시 PR 하겠습니다!

2022-01-14 06:59 UTC, kyeongraekim requested changes
우경님 아래 사항 확인후 수정해주세요!~

2022-01-14 06:59 UTC, kyeongraekim commented on bangguseok_traveller/settings.py
> +# REDIRECT_URI   = 'http://127.0.0.1:8000/users/login/kakao'
사용하지 않은 불필요한 주석은 삭제해주세요!~

2022-01-14 06:59 UTC, kyeongraekim commented on bangguseok_traveller/settings.py
> +ALGORITHM = algorithm
환경 변수에 들어갈 내용은 문자열상수 데이터라고 생각되네요!~ my_settings 내에 선언된 소문자 algorithm 을 컨벤션에 맞게 대문자로 전환해주세요!~

2022-01-14 06:59 UTC, kyeongraekim commented on users/views.py
> +            # print('수정 전 닉네임 :', TEST_USER.nickname)
main에 머지를 희망하는 브랜치 푸시는 정말 실제 상용화될 코드들만 올라와야 합니다. 따라서 디버깅시 사용한 print문이 올라온다면 개발자의 전문성이 다소 반감될 수 있는 행위임을 잊지 말아주세요~

2022-01-14 06:59 UTC, kyeongraekim commented on users/views.py
> +            # print('수정 후 유저 타입 :', user.user_type.name)
해당 내용도 삭제해주세요!~

2022-01-14 06:59 UTC, kyeongraekim commented on users/tests.py
> +        self.assertEqual(kakao_user.kakao_id, 1234567)
유닛테스트는 내가 의도한 뷰파일 내 함수/클래스가 작동을 할 때 발생할 수 있는 모든 성공과 실패의 경우의 수를 테스트를 해본다는데 그 의의가 있습니다. 따라서 위 로그인이 실패할 수 있는 다양한 경우의 수를 고민하여서 추가해보세요!~ 당장 생각나는건 User.DoesNotExist 에러 예외처리가 의도대로 작동하는지 여부가 될 수 있겠네요!~

2022-01-14 06:59 UTC, kyeongraekim commented on users/views.py
> +                print(type(nickname), nickname)
이곳도 불필요한 프린트 문이 보입니다~

2022-01-14 06:59 UTC, kyeongraekim commented on users/views.py
> +                nickname = email.split('@')[0]
닉네임을 이메일에서 뽑아오는 이유가 별도로 있을까요? profile이 전달되지 않았을 때의 에러처리를 적용시키는게 더 나은 기획처럼 보여지네요!~

2022-01-14 08:06 UTC, Bruno-Jang commented on users/views.py
> +                nickname = email.split('@')[0]
프로필 데이터가 넘어오지 않을 때의 문제를 해결하려고 그렇게 설정했었는데 경래님 말씀 보고 팀원분들과 얘기해보니 프론트로 프로필 관련 동의가 필요하다는 메세지를 리턴해주는게 낫겠다고 해서 그렇게 수정했습니다~! 감사합니다!

2022-01-14 10:18 UTC, Bruno-Jang commented on users/tests.py
> +        self.assertEqual(kakao_user.kakao_id, 1234567)
네! 경래님 수정해서 다시 PR했습니다~

2022-01-15 08:33 UTC, kyeongraekim requested changes
우경님 마이너한 수정 소요 다시 한번 짚어 드렸습니다!~ 빠르게 반영해주시면 머지 바로 가능하실 것 같네요!~

2022-01-15 08:33 UTC, kyeongraekim commented on bangguseok_traveller/settings.py
> +# REDIRECT_URI   = 'http://127.0.0.1:8000/users/login/kakao'
주석처리된 내용이 아직 보이는 것 같네요!~

2022-01-15 08:33 UTC, kyeongraekim commented on users/views.py
> +            return JsonResponse({'message': 'USERTYPE_DOESNOTEXIST'}, status=404)
가독성을 위해서 스네이크 케이스로 띄어쓰기를 표현해주세요!~

2022-01-15 08:33 UTC, kyeongraekim commented on users/views.py
> +            profile_json     = profile_request.json()
profile_json 이라는 변수명이 다소 verbose 하게 느껴지네요!~ 단순히 profile이라고 지어도 좋을 것 같습니다!~

2022-01-15 08:42 UTC, Bruno-Jang commented on bangguseok_traveller/settings.py
> +# REDIRECT_URI   = 'http://127.0.0.1:8000/users/login/kakao'
죄송합니다ㅠ 바로 수정하겠습니다!

2022-01-15 10:41 UTC, kyeongraekim approved these changes
LGTM!~

2022-01-15 10:42 UTC, merged