ADD: mainpage view, mainpage test
wecode-bootcamp-korea/28-2nd-BANGGUSEOK-Traveller-backend pull request #5
Opened 2022-01-18 12:47 UTC by seinthemag

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인 페이지 상품 불러오기 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인 페이지 최상단에 모든 상품중 랜덤한 하나의 상품 노출
- order_by('?').first 사용
- 최상단의 랜덤 상품은 각 투표항목의 평균값을 포함하고 있습니다.

2. 가장 최근에 업로드된 상품 4개 노출
- order_by('-create_at'), 인덱싱 사용

3. 모든 상품 노출
-최초 8개 상품이 노출 되고 클라이언트에서 load more 버튼 누르면 8개씩 추가로 불러옴

4. 성공시 Success 메세지와 data, 상태코드 200반환, 존재하지 않는 상품일시 에러 메세지와 상태코드 404반환

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 불러온 쿼리셋을 order_by method를 통해 원하는 방식으로 정렬합니다. 랜덤의 경우 '?'로, 최근상품의 경우 '-created_at'으로 설정했습니다.
- aggregate 메소드를 통해 필드의 값들을 연산하는 방법을 배웠습니다. 
- 최상단에 랜덤한 하나의 상품이 노출되는 부분에 대한 테스트 코드 구현에서 어려움이 있습니다. 우선은 테스트용 데이터를 하나의 상품만 생성하는 방식으로 진행했습니다. 

<br />

## :: 기타 질문 및 특이 사항
- 전체적인 진행상황이 더뎌지고 있어 초기 계획에서 변경이 불가피할것 같습니다.

2022-01-19 01:13 UTC, kyeongraekim requested changes
아래 내용 확인하시고 코멘트 및 수정사항 반영해주세요!~

2022-01-19 01:13 UTC, kyeongraekim commented on products/views.py
> +            new_products  = Product.objects.all().order_by('-created_at')[0:4]
혹시 뒤에 하드코딩으로 인덱싱 되어 있는 부분은 불가피한 설정이었을까요?

2022-01-19 01:13 UTC, kyeongraekim commented on products/views.py
> +                .aggregate(sensibility=Sum('sensibility')/Count('sensibility'))
aggregate에 평균을 내는 내용이 있을 텐데 직접 SUM/COUNT로 나누어주셨네요? 혹시 해당 내용으로 진행하신 이유가 있는지 궁금합니다!~

2022-01-19 01:13 UTC, kyeongraekim commented on products/tests.py
> +                'score'        : [{'sensibility': '9.000000'}, {'intent_to_visit': '9.000000'}, {'impresstion_on_picture':'6.000000'}]
해당 내용도 다른 내용처럼 보기좋게 컨벤션을 맞추어주시면 가독성이 올라갈 것 같습니다!~

2022-01-19 01:13 UTC, kyeongraekim commented on products/views.py
> +            ]
전체 로직을 줄일 수 있어보이는데 오후에 라이브 코드 리뷰 드리면서 봐드릴게요!~

2022-01-19 01:26 UTC, seinthemag commented on products/views.py
> +            new_products  = Product.objects.all().order_by('-created_at')[0:4]
메인에서 최신순 상품을 4개만 띄우기로 해서 추가한 부분입니다. 다른 방법이 있는지 찾아보겠습니다!

2022-01-19 01:51 UTC, seinthemag commented on products/views.py
> +                .aggregate(sensibility=Sum('sensibility')/Count('sensibility'))
단순히 필드값들을 더해서 숫자로 나눠야 한다고 생각했었는데 Avg를 이용하면 간단하게 해결되는거였네요...!

2022-01-19 01:55 UTC, seinthemag commented on products/views.py
> +            ]
감사합니다~!!

2022-01-20 01:29 UTC, kyeongraekim requested changes
작은 부분만 해결해주시면 일단 투표 기능 구현 및 프론트와의 통신을 위해서 머지해드리겠습니다~ 추후에 리팩토링아이디어 또 공유해드릴게요!~

2022-01-20 01:29 UTC, kyeongraekim commented on products/views.py
> +            best_products   = Product.objects.all().order_by('-created_at')[0:4]
- order_by 기준에 따르면 best_products 라는 변수명이 의미적으로 다소 아쉬움이 있어 보이네요!~
-
- 추가사항으로 Product.objects.order_by 로 중간에 all() 호출 없이 진행이 되십니다~ 참고해주세요!

2022-01-20 01:30 UTC, kyeongraekim commented
Conflict는 우경님 유닛테스트 PR까지 반영되면 그 이후에 해결 진행해주세요!~

2022-01-20 01:35 UTC, kyeongraekim commented on products/views.py
> +            vote = Vote.objects.filter(product_id=main_product.id).aggregate(
main_vote_result 라는 변수명이 더 좋아보이네요!~ 개발자에게 있어서 변수 네이밍은 심혈을 기울여야 한다는 사실 잊지말아주세요!~

2022-01-20 01:41 UTC, kyeongraekim requested changes

2022-01-20 01:41 UTC, kyeongraekim commented on products/views.py
> +            random_products = Product.objects.all().order_by('?')[0:4]
ProductAllView로 새롭게 분기가 되셨으니 뒤에 [0:4] 하드 코딩도 offset, limit 선언 이후 디폴트 값을 주어서 진행할 수 있겠네요!~

2022-01-20 08:46 UTC, kyeongraekim approved these changes
다음 내용 진행해주세요~ 우경님 코드 변경 소요가 있을 것을 보이네요!~

2022-01-20 08:47 UTC, merged