제품 리스트 및 태그 필터링 기능 구현
wecode-bootcamp-korea/28-2nd-BANGGUSEOK-Traveller-backend pull request #6
Opened 2022-01-18 16:20 UTC by Bruno-Jang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품 리스트 및 태그 필터링 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 태그 전체 조회

2. 제품 리스트 뷰
- 태그 선택에 따른 조회 기능 구현
- 
3. 유닛 테스트 수정 작업 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 필터링 기능 구현할 때 Q객체를 너무 쓰고 싶어서 이해도 하지 못한 상태로 시작한 점이 너무 아쉽고 반성해야 할 부분이라고 생각합니다.
- 프론트와 백이 같은 이미지를 그리고 프로젝트를 진행하고 있는지 계속 확인해야 함을 느꼈습니다. 다른 팀들이 너무 앞서가고 있다는 생각에 기능만 구현할 생각에 기획 단계에서 충분히 청사진을 그리지 못 했던 점이 아쉽습니다.

<br />

## :: 기타 질문 및 특이 사항
- Q객체를 이해한 후에 리팩토링하겠습니다.
- 힌트를 많이 주셨는데 따라가지 못 해서 너무 아쉬웠습니다... 시간에 너무 쫓겨서 힘들었네요.. 경래님 감사합니다!!

2022-01-19 01:29 UTC, kyeongraekim requested changes
아래 내용 확인해주세요!~ 그리고 테스트 코드도 반영이 될  수 있다면 너무 좋을 것 같네요!~

2022-01-19 01:29 UTC, kyeongraekim commented on products/views.py
> +                products = products.filter(producttag__tag__name=person)
말씀해주신대로 Q객체를 도입하면 중복으로 필터링이 될 수 있는 확장 기획도 추후에 반영이 되겠네요!~ 기대하고 있겠습니다!~

일단 선 도전해주시면 오후에 라이브 코드 리뷰시간에 한 번 봐드릴게요!~

2022-01-19 01:29 UTC, kyeongraekim commented on products/views.py
> +                } for product in products [offset: offset * limit]
그리고 여기는 offset * limit 으로 중간에 곱하기가 되어 있네요? 보통 + 로 덧셈으로 표현하는데 혹시 의도하신 부분일까요?

2022-01-19 01:29 UTC, kyeongraekim commented on products/views.py
> +            ]
이 부분에 대한 가독성도 오후에 봐드리겠습니다!~

2022-01-19 03:51 UTC, Bruno-Jang commented on products/views.py
> +                } for product in products [offset: offset * limit]
네 경래님, 처음에는 +로 했었는데
프론트 정현님께서 * 하는 방식으로 생각하고 하셨다고 해서 이렇게 했습니다.
이렇게 하기도 하나요??

2022-01-19 09:19 UTC, Bruno-Jang commented on products/views.py
> +            ]
경래님.. 다른 부분들 다 정리한 후에 필터링에 Q객체 적용해야 할 것 같아서 이렇게 PR하는데 괜찮을까요..?
다 정리하고 테스트 코드도 작성하겠습니다!

2022-01-19 12:33 UTC, kyeongraekim requested changes
우경님 아래 내용 확인 후 커멘트나 재푸시 부탁드려요!~

2022-01-19 12:33 UTC, kyeongraekim commented on users/views.py
> +###### 시연부분 ######
불필요한 주석이 달려있네요!~

2022-01-19 12:33 UTC, kyeongraekim commented on users/views.py
> +
해당 부분 통신 잘 되셨는지, 유닛테스트 잘 되셨는지 스크린샷으로 확인 부탁드려요!~

2022-01-19 18:16 UTC, Bruno-Jang commented on users/views.py
> +
![스크린샷, 2022-01-20 03-13-47](https://user-images.githubusercontent.com/75561289/150189935-f5895c10-de03-4bf8-b4d8-56f098a0ccea.png)
테스트 코드 한것부터 올리고 오전 중으로 통신한 것도 스크린샷 올리겠습니다~!

2022-01-19 18:23 UTC, Bruno-Jang commented on users/views.py
> +
경래님 users/views.py 에 LogInView 클래스가 2개 중복 생성되어 있어서 (위에 있는 LogInView 클래스가 제가 작성한 클래스) 밑에 있던 LogInView 클래스는 지운 후에 유닛 테스트도 문제 없이 되어서 PR합니다~!

2022-01-20 01:17 UTC, kyeongraekim commented
LGTM!~

2022-01-20 01:19 UTC, kyeongraekim approved these changes

2022-01-20 01:19 UTC, kyeongraekim commented on products/views.py
> +                products = products.filter(producttag__tag__name=person)
해당 부분은 추후에 어제 공유해드린 리팩토링 아이디어 한 번 반영해보세요!~

2022-01-20 01:19 UTC, merged